package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

import (
	"github.com/Tereneckla/wotlk/sim/core/proto"
	"github.com/Tereneckla/wotlk/sim/core/stats"
)

const ExpertisePerQuarterPercentReduction = 3.942308
const HasteRatingPerHastePercent = 15.769233
const CritRatingPerCritChance = 22.076923
const MeleeHitRatingPerHitChance = 15.769233
const SpellHitRatingPerHitChance = 12.615385
const DefenseRatingPerDefense = 2.365385
const DodgeRatingPerDodgeChance = 21.761539
const ParryRatingPerParryChance = 21.761539
const BlockRatingPerBlockChance = 7.884615
const ResilienceRatingPerCritReductionChance = 45.336544

var CritPerAgiMaxLevel = map[proto.Class]float64{
	proto.Class_ClassUnknown:     0.0,
	proto.Class_ClassWarrior:     0.0335,
	proto.Class_ClassPaladin:     0.0403,
	proto.Class_ClassHunter:      0.0250,
	proto.Class_ClassRogue:       0.0250,
	proto.Class_ClassPriest:      0.0401,
	proto.Class_ClassDeathknight: 0.0335,
	proto.Class_ClassShaman:      0.0250,
	proto.Class_ClassMage:        0.0407,
	proto.Class_ClassWarlock:     0.0412,
	proto.Class_ClassDruid:       0.0250,
}
var ExtraClassBaseStats = map[proto.Class]stats.Stats{
	proto.Class_ClassUnknown: {},
	proto.Class_ClassWarrior: {
		stats.Mana:      0.0000,
		stats.SpellCrit: 0.0000 * CritRatingPerCritChance,
		stats.MeleeCrit: 3.1891 * CritRatingPerCritChance,
	},
	proto.Class_ClassPaladin: {
		stats.Mana:      2953.0000,
		stats.SpellCrit: 3.3355 * CritRatingPerCritChance,
		stats.MeleeCrit: 3.2685 * CritRatingPerCritChance,
	},
	proto.Class_ClassHunter: {
		stats.Mana:      3383.0000,
		stats.SpellCrit: 3.6020 * CritRatingPerCritChance,
		stats.MeleeCrit: -1.5320 * CritRatingPerCritChance,
	},
	proto.Class_ClassRogue: {
		stats.Mana:      0.0000,
		stats.SpellCrit: 0.0000 * CritRatingPerCritChance,
		stats.MeleeCrit: -0.2950 * CritRatingPerCritChance,
	},
	proto.Class_ClassPriest: {
		stats.Mana:      2620.0000,
		stats.SpellCrit: 1.2375 * CritRatingPerCritChance,
		stats.MeleeCrit: 3.1765 * CritRatingPerCritChance,
	},
	proto.Class_ClassDeathknight: {
		stats.Mana:      1000.0000,
		stats.SpellCrit: 0.0000 * CritRatingPerCritChance,
		stats.MeleeCrit: 3.1891 * CritRatingPerCritChance,
	},
	proto.Class_ClassShaman: {
		stats.Mana:      2958.0000,
		stats.SpellCrit: 2.2010 * CritRatingPerCritChance,
		stats.MeleeCrit: 2.9220 * CritRatingPerCritChance,
	},
	proto.Class_ClassMage: {
		stats.Mana:      2241.0000,
		stats.SpellCrit: 0.9075 * CritRatingPerCritChance,
		stats.MeleeCrit: 3.4540 * CritRatingPerCritChance,
	},
	proto.Class_ClassWarlock: {
		stats.Mana:      2615.0000,
		stats.SpellCrit: 1.7000 * CritRatingPerCritChance,
		stats.MeleeCrit: 2.6220 * CritRatingPerCritChance,
	},
	proto.Class_ClassDruid: {
		stats.Mana:      2370.0000,
		stats.SpellCrit: 1.8515 * CritRatingPerCritChance,
		stats.MeleeCrit: 7.4755 * CritRatingPerCritChance,
	},
}
